# Generated by Django 3.0.8 on 2020-08-30 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SELLER', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tbl_product_category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('product_stoke', models.IntegerField()),
                ('product_MRP', models.IntegerField()),
                ('product_selling_price', models.IntegerField()),
                ('product_home_img', models.ImageField(upload_to='products_homepage_img')),
                ('is_product_live', models.BooleanField(default=False)),
                ('product_add_datetime_stamp', models.DateTimeField(auto_now_add=True)),
                ('product_category',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.Category')),
                ('product_shop',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SELLER.ShopRegistration')),
            ],
            options={
                'db_table': 'tbl_product',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_output', models.BigIntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.Product')),
            ],
            options={
                'db_table': 'tbl_speaker_details',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.Category')),
            ],
            options={
                'db_table': 'tbl_product_type',
            },
        ),
        migrations.CreateModel(
            name='PowerBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.BigIntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.Product')),
            ],
            options={
                'db_table': 'tbl_power_bank_details',
            },
        ),
        migrations.CreateModel(
            name='PhoneCharger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charger_type',
                 models.CharField(choices=[('Type C', 'Type C'), ('Micro USB', 'Micro USB'), ('Lighting', 'Lighting')],
                                  max_length=50)),
                ('charger_output', models.CharField(max_length=3)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.Product')),
            ],
            options={
                'db_table': 'tbl_phone_charger_details',
            },
        ),
        migrations.CreateModel(
            name='Pendrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.BigIntegerField()),
                ('USB_version', models.CharField(
                    choices=[('USB 2.0', 'USB 2.0'), ('USB 2.1', 'USB 2.1'), ('USB 3.0', 'USB 3.0'),
                             ('USB 3.1', 'USB 3.1')], max_length=50)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.Product')),
            ],
            options={
                'db_table': 'tbl_pendrive_details',
            },
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixel_density', models.CharField(max_length=50)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.Product')),
            ],
            options={
                'db_table': 'tbl_mouse_details',
            },
        ),
        migrations.CreateModel(
            name='MobileDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(
                    choices=[('Android', 'Android'), ('iPhone', 'iPhone'), ('Feature Phone', 'Feature Phone'),
                             ('Tablet', 'Tablet')], max_length=100)),
                ('phone_name', models.CharField(max_length=200)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.Product')),
            ],
            options={
                'db_table': 'tbl_mobile_details',
            },
        ),
        migrations.CreateModel(
            name='MemoryCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.BigIntegerField()),
                ('memory_card_type',
                 models.CharField(choices=[('SD', 'SD'), ('SDHC', 'SDHC'), ('SDXC', 'SDXC')], max_length=50)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.Product')),
            ],
            options={
                'db_table': 'tbl_memory_card_details',
            },
        ),
        migrations.CreateModel(
            name='LaptopDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.TextField()),
                ('description', models.TextField()),
                ('processor', models.CharField(max_length=255)),
                ('RAM', models.IntegerField()),
                ('storage', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.Product')),
            ],
            options={
                'db_table': 'tbl_laptop_details',
            },
        ),
        migrations.CreateModel(
            name='LaptopCharger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charger_output', models.CharField(max_length=3)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.Product')),
            ],
            options={
                'db_table': 'tbl_laptop_charger',
            },
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.TextField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.Product')),
            ],
            options={
                'db_table': 'tbl_keyboard_details',
            },
        ),
        migrations.CreateModel(
            name='Earphones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('earphone_type',
                 models.CharField(choices=[('Wired', 'Wired'), ('Wireless', 'Wireless')], max_length=50)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.Product')),
            ],
            options={
                'db_table': 'tbl_earphone_details',
            },
        ),
    ]
