# Generated by Django 3.0.8 on 2020-08-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('PRODUCT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='mobile', max_length=100),
            preserve_default=False,
        ),
    ]
