# Generated by Django 3.0.8 on 2020-08-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('PRODUCT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='RAM',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='price',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='processor',
            field=models.CharField(default='ad', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='storage',
            field=models.CharField(default='adf', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LaptopVariant',
        ),
    ]
