# Generated by Django 3.0.8 on 2020-08-09 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('PRODUCT', '0002_product_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earphones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('earphone_type', models.CharField(
                    choices=[('Wired', 'Wired'), ('Bluetooth', 'Bluetooth'), ('Truly Wireless', 'Truly Wireless')],
                    max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MobileCharger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charger_output', models.CharField(max_length=3)),
                ('charger_type',
                 models.CharField(choices=[('Type C', 'Type C'), ('Micro USB', 'Micro USB'), ('Lighting', 'Lighting')],
                                  max_length=50)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.Product')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopCharger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charger_output', models.CharField(max_length=3)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.Product')),
            ],
        ),
    ]
