# Generated by Django 3.0.8 on 2020-09-01 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('PRODUCT', '0002_auto_20200830_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptopdetails',
            name='price',
        ),
    ]
