# Generated by Django 3.0.8 on 2020-09-02 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('PRODUCT', '0003_remove_laptopdetails_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='product_details_page_images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.Product')),
            ],
            options={
                'db_table': 'tbl_images_for_detail_page',
            },
        ),
    ]
