# Generated by Django 3.0.8 on 2020-08-09 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('PRODUCT', '0003_earphones_laptopcharger_mobilecharger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MobileCharger',
            new_name='PhoneCharger',
        ),
        migrations.AddField(
            model_name='earphones',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.Product'),
            preserve_default=False,
        ),
    ]
