# Generated by Django 3.0.8 on 2020-08-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('PRODUCT', '0004_auto_20200809_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_product_live',
            field=models.BooleanField(default=False),
        ),
    ]
