# Generated by Django 3.0.8 on 2020-08-01 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=150)),
                ('shop_type', models.CharField(
                    choices=[('Electronic', 'Electronic'), ('Book', 'Book Depot'), ('Clothes', 'Clothes'),
                             ('Grocery', 'Grocery')], max_length=100)),
                ('shop_email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('shop_address', models.TextField()),
                ('shop_phone_number', models.CharField(max_length=13)),
                ('shop_description', models.TextField(blank=True, null=True)),
                ('shop_pincode', models.CharField(max_length=6)),
                ('shop_state', models.CharField(max_length=200)),
                ('shop_city', models.CharField(max_length=200)),
                ('shop_verified', models.BooleanField(default=False)),
                ('owner',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopOwnerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('contact_address', models.TextField()),
                ('TIN_number', models.CharField(max_length=11)),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopOwnerBankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=255)),
                ('account_no', models.CharField(max_length=20)),
                ('IFSC_code', models.CharField(max_length=11)),
                ('PAN_number', models.CharField(max_length=11)),
                ('shop_owner',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('feedback', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('feedback_shop',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SELLER.ShopRegistration')),
                ('feedback_user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
