# Generated by Django 3.0.8 on 2020-07-15 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('feedback', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('feedback_user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopOwnerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_owner_name', models.CharField(max_length=255)),
                ('shop_owner_contact_no', models.CharField(max_length=11)),
                ('shop_owner_email_address', models.EmailField(max_length=254)),
                ('shop_owner_contact_address', models.TextField()),
                ('shop_owner_PAN_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ShopRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255)),
                ('shop_address', models.TextField()),
                ('shop_description', models.TextField()),
                ('shop_email_address', models.EmailField(max_length=254)),
                ('shop_verified', models.BooleanField(default=False)),
                ('shop_state', models.CharField(max_length=200)),
                ('shop_city', models.CharField(max_length=200)),
                ('shop_pincode', models.CharField(max_length=6)),
                ('shop_type', models.CharField(
                    choices=[('Electronic', 'Electronic'), ('Book', 'Book'), ('Clothes', 'Clothes'),
                             ('Grocery', 'Grocery')], max_length=255)),
                ('shop_feedback',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SELLER.ShopFeedback')),
                ('shop_owner',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SELLER.ShopOwnerDetails')),
            ],
        ),
    ]
