# Generated by Django 3.0.8 on 2020-07-15 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('SELLER', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopregistration',
            name='shop_feedback',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='SELLER.ShopFeedback'),
        ),
    ]
