# Generated by Django 3.0.8 on 2020-07-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('SELLER', '0002_auto_20200726_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopownerregistration',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
