# Generated by Django 3.0.8 on 2020-07-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('delivery_address1', models.TextField()),
                ('delivery_address2', models.TextField()),
            ],
        ),
    ]
