# Generated by Django 3.0.8 on 2020-08-30 10:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('USER', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='tbl_user_profile',
        ),
    ]
