# Generated by Django 3.0.8 on 2020-09-04 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('PRODUCT', '0004_productimages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('USER', '0003_usercart'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='cart_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.Product'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
