# Generated by Django 3.0.8 on 2020-09-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('USER', '0004_auto_20200904_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='quantity',
            field=models.PositiveIntegerField(default=1, max_length=1),
        ),
    ]
