# Generated by Django 3.0.8 on 2020-09-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('USER', '0005_auto_20200907_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
