# Generated by Django 3.0.8 on 2020-09-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=10)),
                ('alternate_mobile_no', models.CharField(blank=True, max_length=10, null=True)),
                ('pincode', models.CharField(max_length=6)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=255)),
                ('address_type', models.CharField(choices=[('Home', 'Home'), ('Office', 'Office')], max_length=10)),
                ('order_datetime', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(max_length=255)),
            ],
        ),
    ]
