# Generated by Django 3.0.8 on 2020-09-08 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('PRODUCT', '0004_productimages'),
        ('ORDER', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.Product'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='order',
            table='tbl_user_orders',
        ),
    ]
